const COURSE=window.SQL_COURSE;const STORAGE_KEY='sql-academy-progress-v2';
let db=null,currentLesson=null;const state=loadState();
function loadState(){try{return Object.assign({completed:{},attempts:{},examScore:null,projectDone:false,lastLesson:'select'},JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}catch{return{completed:{},attempts:{},examScore:null,projectDone:false,lastLesson:'select'}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateXP()}
function allLessons(){return COURSE.modules.flatMap(m=>m.lessons.map(l=>({...l,moduleId:m.id,moduleTitle:m.title})))}
function lessonById(id){return allLessons().find(l=>l.id===id)}
function totalXP(){return allLessons().filter(l=>state.completed[l.id]).reduce((s,l)=>s+l.xp,0)+(state.projectDone?500:0)+(state.examScore?state.examScore*20:0)}
function updateXP(){document.getElementById('xpValue').textContent=totalXP()}
function showToast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function initDB(){const SQL=await initSqlJs({locateFile:f=>`https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/${f}`});db=new SQL.Database();db.run(`CREATE TABLE engineers(engineer_id INTEGER PRIMARY KEY,name TEXT NOT NULL,team TEXT NOT NULL,level TEXT NOT NULL);CREATE TABLE tickets(ticket_id INTEGER PRIMARY KEY,engineer_id INTEGER,service TEXT NOT NULL,status TEXT NOT NULL,priority TEXT NOT NULL,created_at TEXT NOT NULL,resolved_at TEXT,resolution_minutes INTEGER,sla_minutes INTEGER NOT NULL,FOREIGN KEY(engineer_id) REFERENCES engineers(engineer_id));INSERT INTO engineers VALUES (1,'Евгений','L&D','L2'),(2,'Анна','Platform','L2'),(3,'Максим','Infra','L2'),(4,'Ирина','Service Desk','L1'),(5,'Олег','Security','L2');INSERT INTO tickets VALUES(1001,1,'VPN','Closed','High','2026-07-01 09:00','2026-07-01 10:10',70,120),(1002,2,'SAP','Open','Medium','2026-07-01 10:20',NULL,NULL,240),(1003,1,'VDI','Closed','High','2026-07-02 08:30','2026-07-02 10:15',105,180),(1004,3,'VDI','Closed','Critical','2026-07-02 09:00','2026-07-02 17:30',510,120),(1005,4,'Outlook','Closed','Low','2026-07-03 11:00','2026-07-03 11:35',35,480),(1006,2,'VPN','Closed','Critical','2026-07-04 08:10','2026-07-04 12:20',250,120),(1007,3,'TCRM','Open','High','2026-07-04 12:00',NULL,NULL,180),(1008,1,'VPN','Closed','Medium','2026-07-05 14:00','2026-07-05 16:15',135,240),(1009,4,'Outlook','Closed','Medium','2026-07-06 09:00','2026-07-06 10:20',80,240),(1010,2,'SAP','Open','High','2026-07-06 11:15',NULL,NULL,180),(1011,3,'TCRM','Closed','Critical','2026-07-07 07:40','2026-07-07 11:40',240,120),(1012,4,'VPN','Open','Low','2026-07-07 13:30',NULL,NULL,480);CREATE INDEX idx_tickets_service ON tickets(service);CREATE INDEX idx_tickets_engineer ON tickets(engineer_id);`)}
function renderNav(){const nav=document.getElementById('moduleNav');nav.innerHTML=`<button data-view="dashboard" class="active">⌂ Панель</button><button data-view="practice">⌘ Все уроки</button><button data-view="review">↻ Повторение</button><button data-view="exam">✓ Экзамен</button><button data-view="project">◆ Финальный проект</button><button data-view="sandbox">_ SQL Sandbox</button>`;nav.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;showView(b.dataset.view);document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('sidebar').classList.remove('open')})}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(name+'View').classList.add('active');const map={dashboard:['Панель обучения','Fast-track SQL для 2nd Support Engineer'],practice:['Карта курса','От основ до инженерного SQL'],review:['Повторение слабых тем','Практика на основе реальных ошибок'],exam:['Итоговый экзамен','Проверь понимание ключевых концепций'],project:['Финальный проект','IT Support Analytics'],sandbox:['SQL Sandbox','Свободная работа с учебной базой']};if(map[name]){screenTitle.textContent=map[name][0];screenSubtitle.textContent=map[name][1]}if(name==='dashboard')renderDashboard();if(name==='practice')renderPractice();if(name==='review')renderReview();if(name==='exam')renderExam();if(name==='project')renderProject();if(name==='sandbox')renderSandbox()}
function renderDashboard(){const lessons=allLessons(),done=lessons.filter(l=>state.completed[l.id]).length,pct=Math.round(done/lessons.length*100),next=lessons.find(l=>!state.completed[l.id])||lessons[lessons.length-1];dashboardView.innerHTML=`<div class="hero"><div class="panel hero-copy"><span class="tag">Персональная программа</span><h2>SQL, который реально пригодится в поддержке.</h2><p>Теория без академической духоты, рабочая SQLite-база, автоматическая проверка и финальный отчёт по IT Support Analytics.</p><button class="primary-btn" onclick="openLesson('${next.id}')">${done?'Продолжить: ':'Начать: '}${next.title}</button></div><div class="panel"><div class="progress-ring" style="--progress:${pct}%"><span>${pct}%</span></div><p class="muted" style="text-align:center">${done} из ${lessons.length} уроков</p></div></div><div class="grid cols-3"><div class="panel stat"><span class="muted">Заработано</span><strong>${totalXP()} XP</strong></div><div class="panel stat"><span class="muted">Экзамен</span><strong>${state.examScore===null?'—':state.examScore+'/5'}</strong></div><div class="panel stat"><span class="muted">Финальный проект</span><strong>${state.projectDone?'Готов':'Впереди'}</strong></div></div><h2>Модули</h2><div class="grid cols-2">${COURSE.modules.map(m=>{const md=m.lessons.filter(l=>state.completed[l.id]).length;return`<article class="panel module-card" onclick="showView('practice')"><span class="tag">${m.icon}</span><h3>${m.title}</h3><p class="muted">${m.description}</p><strong>${md}/${m.lessons.length}</strong></article>`}).join('')}</div>`}
function renderPractice(){practiceView.innerHTML=COURSE.modules.map(m=>`<div class="panel" style="margin-bottom:18px"><h2>${m.icon} · ${m.title}</h2><p class="muted">${m.description}</p><div class="lesson-list">${m.lessons.map(l=>lessonRow(l)).join('')}</div></div>`).join('')}
function lessonRow(l){const a=state.attempts[l.id]||0,weak=a>=3&&!state.completed[l.id];return`<div class="lesson-row"><span class="status-dot ${state.completed[l.id]?'done':weak?'weak':''}"></span><div><strong>${l.title}</strong><div class="muted">${l.difficulty} · ${l.xp} XP${a?` · попыток: ${a}`:''}</div></div><button class="secondary-btn" onclick="openLesson('${l.id}')">${state.completed[l.id]?'Повторить':'Открыть'}</button></div>`}
function openLesson(id){currentLesson=lessonById(id);state.lastLesson=id;saveState();showView('lesson');screenTitle.textContent=currentLesson.title;screenSubtitle.textContent=currentLesson.moduleTitle;lessonView.innerHTML=`<div class="lesson-layout"><article class="panel lesson-content"><span class="tag">${currentLesson.difficulty} · ${currentLesson.xp} XP</span><h2>${currentLesson.title}</h2>${currentLesson.theory}<h3>Задание</h3><p>${currentLesson.task}</p><h3>Подсказки</h3><ol>${currentLesson.hints.map(h=>`<li>${h}</li>`).join('')}</ol></article><aside class="panel editor-panel"><div class="editor-toolbar"><strong>SQL Editor</strong><span class="muted">SQLite</span></div><textarea id="lessonEditor" class="sql-editor" spellcheck="false">${currentLesson.starter}</textarea><div class="button-row"><button class="primary-btn" onclick="runLesson()">Выполнить и проверить</button><button class="secondary-btn" onclick="showSolution()">Показать решение</button></div><div id="lessonFeedback" class="feedback"></div><div id="lessonResult" class="result-wrap"></div></aside></div>`}
function execSQL(sql){const trimmed=sql.trim();if(!trimmed)throw new Error('Запрос пуст.');if(/\b(?:DROP|DELETE|UPDATE|INSERT|ALTER|ATTACH|DETACH|PRAGMA)\b/i.test(trimmed))throw new Error('В учебном режиме разрешены только безопасные запросы чтения.');const res=db.exec(trimmed);if(!res.length)return{columns:[],values:[]};return res[res.length-1]}
function renderTable(result,target){if(!result.columns.length){target.innerHTML='<p class="muted" style="padding:12px">Запрос выполнен, но строк нет.</p>';return}target.innerHTML=`<table><thead><tr>${result.columns.map(c=>`<th>${escapeHTML(c)}</th>`).join('')}</tr></thead><tbody>${result.values.map(r=>`<tr>${r.map(v=>`<td>${escapeHTML(v===null?'NULL':String(v))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function normalize(v){return typeof v==='number'?Math.round(v*10)/10:v}
function validateResult(result,v){if(v.explainContains)return result.values.flat().join(' ').includes(v.explainContains);if(v.columns&&JSON.stringify(result.columns)!==JSON.stringify(v.columns))return false;if(Number.isInteger(v.rows)&&result.values.length!==v.rows)return false;if(v.orderedFirst&&JSON.stringify(result.values[0]?.map(normalize))!==JSON.stringify(v.orderedFirst.map(normalize)))return false;if(v.includes&&!result.values.some(r=>JSON.stringify(r.map(normalize))===JSON.stringify(v.includes.map(normalize))))return false;return true}
function diagnose(err,sql,lesson){const m=String(err.message||err);if(/syntax error/i.test(m))return'Синтаксическая ошибка: проверь запятые, скобки и порядок SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY.';if(/no such column/i.test(m))return'Такого столбца нет. Сверь имя поля со схемой учебной базы.';if(/ambiguous column/i.test(m))return'Имя столбца неоднозначно. Добавь алиас таблицы, например t.service.';if(/misuse of aggregate/i.test(m))return'Агрегат используется не в том месте. Для фильтрации групп нужен HAVING.';if(sql.includes('= NULL'))return'NULL нельзя сравнивать через =. Используй IS NULL или IS NOT NULL.';return lesson?.hints?.[Math.min((state.attempts[lesson.id]||1)-1,lesson.hints.length-1)]||m}
function runLesson(){const sql=lessonEditor.value,fb=lessonFeedback;state.attempts[currentLesson.id]=(state.attempts[currentLesson.id]||0)+1;try{const result=execSQL(sql);renderTable(result,lessonResult);const ok=validateResult(result,currentLesson.validate);fb.className='feedback show '+(ok?'success':'error');fb.innerHTML=ok?'<strong>Верно.</strong> Запрос возвращает ожидаемый результат.':'<strong>Пока не сошлось.</strong> '+diagnose(new Error('Результат отличается от ожидаемого.'),sql,currentLesson);if(ok){state.completed[currentLesson.id]=true;showToast(`Урок пройден: +${currentLesson.xp} XP`)}saveState()}catch(e){fb.className='feedback show error';fb.innerHTML='<strong>Ошибка запроса.</strong> '+diagnose(e,sql,currentLesson);saveState()}}
function showSolution(){lessonEditor.value=currentLesson.solution;showToast('Решение вставлено. Разбери его и выполни самостоятельно.')}
function renderReview(){const weak=allLessons().filter(l=>(state.attempts[l.id]||0)>=2&&!state.completed[l.id]).sort((a,b)=>(state.attempts[b.id]||0)-(state.attempts[a.id]||0));const repeat=weak.length?weak:allLessons().filter(l=>state.completed[l.id]).slice(-4).reverse();reviewView.innerHTML=`<div class="panel"><h2>${weak.length?'Темы, где были сложности':'Закрепление изученного'}</h2><p class="muted">Список строится по числу неудачных попыток. Повторение не отнимает прогресс.</p><div class="lesson-list">${repeat.length?repeat.map(lessonRow).join(''):'<p>Сначала пройди хотя бы один урок.</p>'}</div></div>`}
function renderExam(){examView.innerHTML=`<form id="examForm" class="panel"><h2>Итоговый экзамен</h2>${COURSE.exam.map((q,i)=>`<div class="exam-question"><strong>${i+1}. ${q.q}</strong>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}">${o}</label>`).join('')}</div>`).join('')}<button class="primary-btn" type="submit">Проверить экзамен</button><div id="examFeedback" class="feedback"></div></form>`;examForm.onsubmit=e=>{e.preventDefault();let score=0;COURSE.exam.forEach((q,i)=>{const v=new FormData(examForm).get('q'+i);if(Number(v)===q.answer)score++});state.examScore=score;saveState();examFeedback.className='feedback show '+(score>=4?'success':'error');examFeedback.innerHTML=`Результат: <strong>${score}/5</strong>. ${score>=4?'Экзамен сдан.':'Повтори слабые темы и попробуй ещё раз.'}`}}
function renderProject(){const p=COURSE.project;projectView.innerHTML=`<div class="lesson-layout"><article class="panel lesson-content"><span class="tag">Финал · 500 XP</span><h2>${p.title}</h2><p>${p.description}</p><p>Критерии: один CTE, агрегаты, CASE для SLA, оконный рейтинг и стабильная сортировка.</p></article><aside class="panel editor-panel"><textarea id="projectEditor" class="sql-editor">${p.starter}</textarea><div class="button-row"><button class="primary-btn" onclick="runProject()">Проверить проект</button></div><div id="projectFeedback" class="feedback"></div><div id="projectResult" class="result-wrap"></div></aside></div>`}
function runProject(){try{const r=execSQL(projectEditor.value);renderTable(r,projectResult);const ok=validateResult(r,COURSE.project.validate);projectFeedback.className='feedback show '+(ok?'success':'error');projectFeedback.innerHTML=ok?'<strong>Проект принят.</strong> Ты собрал полноценный аналитический отчёт.':'Результат пока не совпадает с требованиями. Проверь CTE, агрегаты и порядок сортировки.';if(ok)state.projectDone=true;saveState()}catch(e){projectFeedback.className='feedback show error';projectFeedback.textContent=diagnose(e,projectEditor.value)}}
function renderSandbox(){sandboxView.innerHTML=`<div class="lesson-layout"><article class="panel"><h2>Схема базы</h2><pre class="code-block">engineers(engineer_id, name, team, level)\n\ntickets(ticket_id, engineer_id, service, status, priority, created_at, resolved_at, resolution_minutes, sla_minutes)</pre><p class="muted">Попробуй собственные SELECT, JOIN, CTE, оконные функции и EXPLAIN QUERY PLAN.</p></article><aside class="panel"><textarea id="sandboxEditor" class="sql-editor">SELECT service, COUNT(*) AS tickets_count\nFROM tickets\nGROUP BY service\nORDER BY tickets_count DESC;</textarea><div class="button-row"><button class="primary-btn" onclick="runSandbox()">Выполнить</button></div><div id="sandboxFeedback" class="feedback"></div><div id="sandboxResult" class="result-wrap"></div></aside></div>`}
function runSandbox(){try{const r=execSQL(sandboxEditor.value);renderTable(r,sandboxResult);sandboxFeedback.className='feedback show success';sandboxFeedback.textContent=`Готово. Строк: ${r.values.length}`;}catch(e){sandboxFeedback.className='feedback show error';sandboxFeedback.textContent=diagnose(e,sandboxEditor.value)}}
function escapeHTML(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.openLesson=openLesson;window.showView=showView;window.runLesson=runLesson;window.showSolution=showSolution;window.runProject=runProject;window.runSandbox=runSandbox;
document.getElementById('menuBtn').onclick=()=>sidebar.classList.toggle('open');document.getElementById('continueBtn').onclick=()=>openLesson(state.lastLesson||'select');document.getElementById('resetProgressBtn').onclick=()=>{if(confirm('Сбросить весь прогресс курса?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};
(async()=>{renderNav();updateXP();try{await initDB();renderDashboard()}catch(e){dashboardView.innerHTML=`<div class="panel"><h2>Не удалось загрузить SQLite</h2><p>${escapeHTML(e.message)}</p><p class="muted">Проверь доступ к CDN и обнови страницу.</p></div>`}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})})();
