window.SQL_COURSE = {
  modules: [
    {id:'fundamentals',title:'Основы SQL',icon:'01',description:'SELECT, фильтрация, сортировка, NULL',lessons:[
      {id:'select',title:'SELECT: достаём данные',xp:80,difficulty:'Новичок',theory:`<p><strong>SELECT</strong> отвечает на главный вопрос: какие столбцы и из какой таблицы нам нужны.</p><pre class="code-block">SELECT ticket_id, service, status\nFROM tickets;</pre><p>Не привыкай к <code>SELECT *</code> в рабочих запросах: явный список полей проще читать и безопаснее поддерживать.</p>`,starter:'SELECT ticket_id, service, status\nFROM tickets;',task:'Выведи ticket_id, service и status из tickets. Отсортируй по ticket_id.',solution:'SELECT ticket_id, service, status FROM tickets ORDER BY ticket_id;',validate:{columns:['ticket_id','service','status'],rows:12,orderedFirst:[1001,'VPN','Closed']},hints:['Добавь ORDER BY ticket_id в конец.','Нужны ровно три поля: ticket_id, service, status.']},
      {id:'where',title:'WHERE: фильтруем инциденты',xp:90,difficulty:'Новичок',theory:`<p><strong>WHERE</strong> оставляет только строки, которые соответствуют условию.</p><pre class="code-block">SELECT *\nFROM tickets\nWHERE priority = 'Critical';</pre><p>Строковые значения заключаются в одинарные кавычки.</p>`,starter:"SELECT ticket_id, service, priority\nFROM tickets\nWHERE ",task:"Найди все тикеты с приоритетом Critical.",solution:"SELECT ticket_id, service, priority FROM tickets WHERE priority = 'Critical' ORDER BY ticket_id;",validate:{columns:['ticket_id','service','priority'],rows:3,includes:[1004,'VDI','Critical']},hints:["Сравни priority со строкой 'Critical'.",'Не забудь оператор =.']},
      {id:'null',title:'NULL и неизвестные значения',xp:100,difficulty:'База',theory:`<p><code>NULL</code> означает отсутствие известного значения. С ним нельзя использовать обычное равенство.</p><pre class="code-block">WHERE resolved_at IS NULL</pre>`,starter:'SELECT ticket_id, status, resolved_at\nFROM tickets\nWHERE ',task:'Покажи незакрытые тикеты, у которых resolved_at отсутствует.',solution:'SELECT ticket_id, status, resolved_at FROM tickets WHERE resolved_at IS NULL ORDER BY ticket_id;',validate:{columns:['ticket_id','status','resolved_at'],rows:4,includes:[1002,'Open',null]},hints:['Используй IS NULL, а не = NULL.','Фильтр должен применяться к resolved_at.']}
    ]},
    {id:'analytics',title:'Аналитика',icon:'02',description:'GROUP BY, HAVING, CASE, даты',lessons:[
      {id:'group',title:'GROUP BY и агрегаты',xp:120,difficulty:'Рабочий',theory:`<p>Агрегаты сворачивают множество строк в показатели: <code>COUNT</code>, <code>AVG</code>, <code>SUM</code>, <code>MIN</code>, <code>MAX</code>.</p><pre class="code-block">SELECT service, COUNT(*) AS tickets_count\nFROM tickets\nGROUP BY service;</pre>`,starter:'SELECT service, COUNT(*) AS tickets_count\nFROM tickets\nGROUP BY service\nORDER BY ',task:'Посчитай количество тикетов по сервисам и выведи от большего к меньшему.',solution:'SELECT service, COUNT(*) AS tickets_count FROM tickets GROUP BY service ORDER BY tickets_count DESC, service;',validate:{columns:['service','tickets_count'],rows:5,orderedFirst:['VPN',4]},hints:['Сортируй по псевдониму tickets_count DESC.','Добавь вторичную сортировку по service для стабильного результата.']},
      {id:'having',title:'HAVING: фильтруем группы',xp:120,difficulty:'Рабочий',theory:`<p><code>WHERE</code> фильтрует строки до группировки, а <code>HAVING</code> — готовые группы.</p>`,starter:'SELECT service, COUNT(*) AS tickets_count\nFROM tickets\nGROUP BY service\nHAVING ',task:'Покажи только сервисы, у которых не меньше 2 тикетов.',solution:'SELECT service, COUNT(*) AS tickets_count FROM tickets GROUP BY service HAVING COUNT(*) >= 2 ORDER BY tickets_count DESC, service;',validate:{columns:['service','tickets_count'],rows:5,includes:['VPN',4]},hints:['Условие по COUNT(*) пишется после GROUP BY.','Используй >= 2.']},
      {id:'case',title:'CASE: бизнес-логика в запросе',xp:130,difficulty:'Рабочий',theory:`<p><code>CASE</code> позволяет классифицировать данные прямо в SQL.</p><pre class="code-block">CASE\n  WHEN resolution_minutes > sla_minutes THEN 'Breach'\n  ELSE 'OK'\nEND</pre>`,starter:"SELECT ticket_id,\nCASE\n  WHEN \n  ELSE 'OK'\nEND AS sla_state\nFROM tickets\nORDER BY ticket_id;",task:"Для каждого тикета выведи sla_state: 'Breach', если resolution_minutes больше sla_minutes, иначе 'OK'. Незакрытые тикеты тоже считаются OK в этой задаче.",solution:"SELECT ticket_id, CASE WHEN resolution_minutes > sla_minutes THEN 'Breach' ELSE 'OK' END AS sla_state FROM tickets ORDER BY ticket_id;",validate:{columns:['ticket_id','sla_state'],rows:12,includes:[1004,'Breach']},hints:['Сравни resolution_minutes и sla_minutes.','В SQLite сравнение с NULL не истинно, поэтому ELSE даст OK.']}
    ]},
    {id:'relations',title:'Связи таблиц',icon:'03',description:'JOIN, LEFT JOIN, подзапросы',lessons:[
      {id:'join',title:'INNER JOIN',xp:150,difficulty:'Ключевая тема',theory:`<p><strong>JOIN</strong> соединяет связанные таблицы по ключу. Здесь <code>tickets.engineer_id</code> указывает на <code>engineers.engineer_id</code>.</p>`,starter:'SELECT t.ticket_id, e.name AS engineer, t.service\nFROM tickets t\nJOIN engineers e ON ',task:'Соедини tickets и engineers и покажи ticket_id, имя инженера и сервис.',solution:'SELECT t.ticket_id, e.name AS engineer, t.service FROM tickets t JOIN engineers e ON t.engineer_id = e.engineer_id ORDER BY t.ticket_id;',validate:{columns:['ticket_id','engineer','service'],rows:12,orderedFirst:[1001,'Артём','VPN']},hints:['Свяжи t.engineer_id с e.engineer_id.','Добавь ORDER BY t.ticket_id.']},
      {id:'leftjoin',title:'LEFT JOIN: не теряем строки',xp:160,difficulty:'Ключевая тема',theory:`<p><code>LEFT JOIN</code> сохраняет все строки левой таблицы, даже если совпадений справа нет.</p>`,starter:'SELECT e.name, COUNT(t.ticket_id) AS tickets_count\nFROM engineers e\nLEFT JOIN tickets t ON \nGROUP BY e.engineer_id, e.name\nORDER BY tickets_count DESC, e.name;',task:'Покажи всех инженеров, включая инженера без тикетов, и количество их тикетов.',solution:'SELECT e.name, COUNT(t.ticket_id) AS tickets_count FROM engineers e LEFT JOIN tickets t ON e.engineer_id = t.engineer_id GROUP BY e.engineer_id, e.name ORDER BY tickets_count DESC, e.name;',validate:{columns:['name','tickets_count'],rows:5,includes:['Олег',0]},hints:['Левой таблицей должна быть engineers.','Считай COUNT(t.ticket_id), не COUNT(*).']},
      {id:'subquery',title:'Подзапросы',xp:170,difficulty:'Продвинутый',theory:`<p>Подзапрос может вычислить порог, который затем использует внешний запрос.</p>`,starter:'SELECT ticket_id, resolution_minutes\nFROM tickets\nWHERE resolution_minutes > (\n  SELECT \n  FROM tickets\n)\nORDER BY resolution_minutes DESC;',task:'Найди закрытые тикеты, чьё время решения выше среднего среди закрытых тикетов.',solution:'SELECT ticket_id, resolution_minutes FROM tickets WHERE resolution_minutes > (SELECT AVG(resolution_minutes) FROM tickets WHERE resolution_minutes IS NOT NULL) ORDER BY resolution_minutes DESC;',validate:{columns:['ticket_id','resolution_minutes'],rows:4,orderedFirst:[1004,510]},hints:['В подзапросе нужен AVG(resolution_minutes).','Исключи NULL внутри среднего.']}
    ]},
    {id:'advanced',title:'Продвинутый SQL',icon:'04',description:'CTE, окна, индексы и EXPLAIN',lessons:[
      {id:'cte',title:'CTE: читаемые этапы запроса',xp:190,difficulty:'Продвинутый',theory:`<p><code>WITH</code> создаёт именованный промежуточный результат. Это делает сложный запрос похожим на последовательность понятных шагов.</p>`,starter:'WITH service_stats AS (\n  SELECT service, COUNT(*) AS tickets_count\n  FROM tickets\n  GROUP BY service\n)\nSELECT \nFROM service_stats\nWHERE tickets_count >= 2\nORDER BY tickets_count DESC, service;',task:'Через CTE посчитай тикеты по сервисам и оставь сервисы с количеством не меньше 2.',solution:'WITH service_stats AS (SELECT service, COUNT(*) AS tickets_count FROM tickets GROUP BY service) SELECT service, tickets_count FROM service_stats WHERE tickets_count >= 2 ORDER BY tickets_count DESC, service;',validate:{columns:['service','tickets_count'],rows:5,orderedFirst:['VPN',4]},hints:['Во внешнем SELECT укажи service, tickets_count.','Фильтрация CTE выполняется во внешнем запросе.']},
      {id:'window',title:'Оконные функции и рейтинг',xp:220,difficulty:'Продвинутый',theory:`<p>Оконные функции считают показатели, не схлопывая строки. <code>RANK() OVER (...)</code> создаёт рейтинг.</p>`,starter:'WITH engineer_stats AS (\n  SELECT e.name, COUNT(t.ticket_id) AS tickets_count\n  FROM engineers e\n  LEFT JOIN tickets t ON e.engineer_id = t.engineer_id\n  GROUP BY e.engineer_id, e.name\n)\nSELECT name, tickets_count,\n       RANK() OVER (ORDER BY ) AS engineer_rank\nFROM engineer_stats\nORDER BY engineer_rank, name;',task:'Построй рейтинг инженеров по количеству тикетов: больше тикетов — выше место.',solution:'WITH engineer_stats AS (SELECT e.name, COUNT(t.ticket_id) AS tickets_count FROM engineers e LEFT JOIN tickets t ON e.engineer_id = t.engineer_id GROUP BY e.engineer_id, e.name) SELECT name, tickets_count, RANK() OVER (ORDER BY tickets_count DESC) AS engineer_rank FROM engineer_stats ORDER BY engineer_rank, name;',validate:{columns:['name','tickets_count','engineer_rank'],rows:5,includes:['Артём',3,1]},hints:['Внутри окна сортируй tickets_count DESC.','RANK() вызывается без аргументов.']},
      {id:'explain',title:'Индексы и EXPLAIN QUERY PLAN',xp:220,difficulty:'Инженерный',theory:`<p>Индекс ускоряет поиск ценой дополнительного места и стоимости записи. <code>EXPLAIN QUERY PLAN</code> показывает стратегию SQLite.</p><pre class="code-block">CREATE INDEX idx_tickets_service ON tickets(service);\nEXPLAIN QUERY PLAN SELECT * FROM tickets WHERE service='VPN';</pre>`,starter:"EXPLAIN QUERY PLAN\nSELECT ticket_id, service\nFROM tickets\nWHERE service = 'VPN';",task:'Выполни EXPLAIN QUERY PLAN для поиска VPN-тикетов. Индекс уже создан учебной базой.',solution:"EXPLAIN QUERY PLAN SELECT ticket_id, service FROM tickets WHERE service = 'VPN';",validate:{explainContains:'idx_tickets_service'},hints:['Запрос должен начинаться с EXPLAIN QUERY PLAN.',"Фильтр: service = 'VPN'."]}
    ]}
  ],
  exam:[
    {q:'Какой оператор фильтрует строки до GROUP BY?',options:['HAVING','WHERE','ORDER BY','OVER'],answer:1},
    {q:'Как сохранить все строки левой таблицы?',options:['INNER JOIN','CROSS JOIN','LEFT JOIN','UNION'],answer:2},
    {q:'Как корректно проверить отсутствие значения?',options:['= NULL','IS NULL','NULL()','EMPTY'],answer:1},
    {q:'Что делает PARTITION BY?',options:['Удаляет дубли','Делит окно на группы','Создаёт индекс','Фильтрует таблицу'],answer:1},
    {q:'Для чего используют EXPLAIN QUERY PLAN?',options:['Изменить схему','Посмотреть план выполнения','Экспортировать таблицу','Создать CTE'],answer:1}
  ],
  project:{title:'Финальный проект: IT Support Analytics',description:'Собери единый аналитический отчёт по сервисам вымышленной компании T-Bonk: количество тикетов, число нарушений SLA, среднее время решения и место сервиса по нагрузке.',starter:`WITH service_stats AS (\n  SELECT\n    service,\n    COUNT(*) AS tickets_count,\n    SUM(CASE WHEN resolution_minutes > sla_minutes THEN 1 ELSE 0 END) AS sla_breaches,\n    ROUND(AVG(resolution_minutes), 1) AS avg_resolution\n  FROM tickets\n  WHERE resolution_minutes IS NOT NULL\n  GROUP BY service\n)\nSELECT\n  service,\n  tickets_count,\n  sla_breaches,\n  avg_resolution,\n  RANK() OVER (ORDER BY tickets_count DESC) AS load_rank\nFROM service_stats\nORDER BY load_rank, service;`,validate:{columns:['service','tickets_count','sla_breaches','avg_resolution','load_rank'],rows:5,orderedFirst:['VPN',3,1,151.7,1]}}
};