import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { loadProductIdentity, productFullTitle } from './product-identity';

const root = resolve(import.meta.dirname, '..');
const checkOnly = process.argv.includes('--check');
const identity = loadProductIdentity(root);

const generatedModulePath = resolve(root, 'src/generated/product-identity.ts');
const manifestPath = resolve(root, 'public/manifest.webmanifest');

const generatedModule = `// Generated by scripts/generate-product-identity.ts. Do not edit directly.\n\nexport const productIdentity = ${JSON.stringify(identity, null, 2)} as const;\n\nexport const productFullTitle = ${JSON.stringify(productFullTitle(identity))};\n\nexport type ProductIdentity = typeof productIdentity;\n`;

const manifest = `${JSON.stringify({
  name: productFullTitle(identity),
  short_name: identity.shortName,
  description: identity.description,
  lang: identity.locale,
  dir: 'ltr',
  start_url: './',
  scope: './',
  display: 'standalone',
  theme_color: '#07130f',
  background_color: '#07130f',
  icons: [
    { src: './pwa-192.png', sizes: '192x192', type: 'image/png' },
    { src: './pwa-512.png', sizes: '512x512', type: 'image/png' }
  ]
}, null, 2)}\n`;

function verify(path: string, expected: string) {
  if (!existsSync(path)) throw new Error(`${path.replace(`${root}/`, '')} is missing`);
  const actual = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
  if (actual !== expected) {
    throw new Error(`${path.replace(`${root}/`, '')} is stale; run npm run identity:generate`);
  }
}

if (checkOnly) {
  verify(generatedModulePath, generatedModule);
  verify(manifestPath, manifest);
  console.log(`Product identity artifacts match ${identity.contract}: ${identity.productName}.`);
} else {
  mkdirSync(dirname(generatedModulePath), { recursive: true });
  writeFileSync(generatedModulePath, generatedModule);
  writeFileSync(manifestPath, manifest);
  console.log(`Generated product identity artifacts for ${identity.productName}.`);
}
